project/bartorelli/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.http import HttpResponse
from django.views.generic import TemplateView

from core import RunEnvironment
from core.sitemap import CMSSitemapByLanguage
from core.views import sitemap_index
from products.views import check_import, import_products

urlpatterns = i18n_patterns('',
                            url(r'^admin/', include(admin.site.urls)),
                            url(r'^accounts/', include('custom_auth.urls', namespace='user')),
                            )

if settings.DEBUG:
    urlpatterns = [
                      url(r'^import/$', check_import),
                      url(r'^import/result/$', import_products, name='import_result'),

                      url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
                          {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
                      url(r'', include('django.contrib.staticfiles.urls')),
                  ] + urlpatterns

# ==========================================================================
# robots.txt
# ==========================================================================
if RunEnvironment.current_env() == RunEnvironment.LIVE:
    urlpatterns += [
        url(r'^robots\.txt$',
            TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    ]
else:
    urlpatterns += [
        url(r'^robots\.txt$',
            lambda r: HttpResponse("User-agent: *\nDisallow: /", mimetype="text/plain")),
    ]

# ==========================================================================
# sitemap.xml
# ==========================================================================

sitemaps = {
    'cmspages': CMSSitemapByLanguage
}

urlpatterns += [
    url(r'paypal\/payment', 'core.utils.show_me_the_money', name='show_me_the_money'),
]

urlpatterns += [
    url(r'^sitemap\.xml$', sitemap_index, name="sitemap_xml_index"),
]
urlpatterns += i18n_patterns(
    # url(r'^notify/$', include('paypal.standard.ipn.urls'), name='paypal-ipn'),
    url(r'^search/$', TemplateView.as_view(template_name='core/common/google_search.html'),
        name='google-search'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='sitemap_xml'),
    url(r'^', include('cms.urls')),
)

project/contacts/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
                       url(r'^$', 'contacts.views.contact_form', name='contact_form'),
                       url(r'^branch_admin_visibility.js$', 'core.views.branch_admin_visibility_js',
                           name='branch_admin_visibility_js'),
                       url(r'^notify_changes/(?P<app_name>[\w+-]*)/(?P<model_name>[\w+-]*)/(?P<obj_pk>\d+)/',
                           'core.views.notify_changes', name='notify_changes'),
                       )

project/custom_auth/urls.py
from django.conf.urls import patterns, url

from custom_auth import views
from custom_auth.forms import ProfilePasswordResetForm


urlpatterns = patterns('',
                       url(r'^create/$', views.create_user, name='create_user'),
                       url(r'^login/$', views.login_user, name='login_user'),
                       url(r'^complete/$', views.complete_registration, name='complete_registration'),

                       url(r'^logout/$', views.logout_user, name='logout_user'),

                       url(r'^profile/$', views.change_user, name='change_user_data'),

                       url(r'^password_reset/$', 'django.contrib.auth.views.password_reset', {
                           'template_name': 'custom_auth/password_reset_form.html',
                           'post_reset_redirect': 'user:password_reset_done',
                           'email_template_name': 'custom_auth/password_reset_email.html',
                           'password_reset_form': ProfilePasswordResetForm
                       }, name='password_reset'),

                       url(r'^password-reset/done/$', 'django.contrib.auth.views.password_reset_done', {
                           'template_name': 'custom_auth/password_reset_done.html'
                       }, name='password_reset_done'),

                       url(r'^reset/(?P<uidb64>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                           'django.contrib.auth.views.password_reset_confirm',
                           {
                               'template_name': 'custom_auth/password_reset_confirm.html',
                               'post_reset_redirect': 'user:password_reset_complete'
                           }, name='password_reset_confirm'),

                       url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete',
                           {'template_name': 'custom_auth/password_reset_complete.html'},
                           name='password_reset_complete'),

                       url(r'^password-change/$', 'django.contrib.auth.views.password_change', {
                           'post_change_redirect': 'user:password_change_done',
                           'template_name': 'custom_auth/change_user_password.html',
                       }, name='change_user_password'),

                       url(r'^password-change/done/$', 'django.contrib.auth.views.password_change_done', {
                           'template_name': 'custom_auth/password_change_done.html',
                       }, name='password_change_done'),

                       )

project/custom_auth/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.core import validators
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _


class CustomAbstractUser(AbstractBaseUser, PermissionsMixin):
    """
    An abstract base class implementing a fully featured User model with
    admin-compliant permissions.

    Username, password and email are required. Other fields are optional.
    """
    username = models.CharField(_('username'), max_length=30, unique=True,
                                help_text=_('Required. 30 characters or fewer. Letters, digits and '
                                            '@/./+/-/_ only.'),
                                validators=[
                                    validators.RegexValidator(r'^[\w.@+-]+$', _('Enter a valid username.'), 'invalid')
                                ])
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)
    email = models.EmailField(_('email address'), blank=True)

    privacy_ok = models.BooleanField(_('privacy_accept'), blank=True)

    is_staff = models.BooleanField(_('staff status'), default=False,
                                   help_text=_('Designates whether the user can log into this admin '
                                               'site.'))
    is_active = models.BooleanField(_('active'), default=True,
                                    help_text=_('Designates whether this user should be treated as '
                                                'active. Unselect this instead of deleting accounts.'))
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = _('User')
        verbose_name_plural = _('Users')
        abstract = True

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """
        Returns the short name for the user.
        """
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email], **kwargs)


class CustomUser(CustomAbstractUser):
    def get_app_related_users(self, app_name, model_name):
        """
        App related users:

        are those user with access to the admin for <app> and, at least one different enabled language.

        [] (empty list) when:
            current user is superuser
            current user is not active
            current user have no staff privileges
            current user have no permission for <app>
            current user have no enabled languages

        Args:
            app_name:
            name of the app we want to check for related admin users

        Returns:

        """
        empty_result = []
        permissions_to_check = ['%s.change_%s' % (app_name, model_name)]  # ['%s.change_news' % app_name]

        # check for early return
        empty_result_conditions = self.is_superuser
        empty_result_conditions = empty_result_conditions or not self.is_active
        empty_result_conditions = empty_result_conditions or not self.is_staff
        empty_result_conditions = empty_result_conditions or not self.has_perms(permissions_to_check)

        # filtering related users
        users = CustomUser.objects.filter(is_staff=True, is_active=True, is_superuser=True)
        # .exclude(is_superuser=True).exclude(pk=self.pk)

        related_users = []
        for user in users:
            if user.has_perms(permissions_to_check):
                related_users.append(user)

        return related_users

project/custom_auth/forms.py
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm, UserChangeForm
from custom_auth.models import CustomUser
from django import forms


class Registration(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    privacy_ok = forms.BooleanField(required=True)

    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'privacy_ok',)


class ProfilePasswordResetForm(PasswordResetForm):
    pass


class ProfileChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ("username", "first_name", "last_name", "email",)

    def clean_password(self):
        """
        password is not in the form so I can pass the validation
        """
        pass

project/custom_auth/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.views.decorators.cache import never_cache

from custom_auth.forms import Registration, ProfileChangeForm


def create_user(request):

    if request.method == 'POST':
        form = Registration(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('user:complete_registration'))
    else:
        form = Registration()

    context = {
        'form': form
    }
    return render(request, 'custom_auth/user_creation.html', context)


def complete_registration(request):
    context = {
        'message_registration_ok': "Congratulazioni ti sei registrato correttamente, ora puoi procedere a loggarti."
    }
    return render(request, 'custom_auth/complete_registration.html', context)


def login_user(request):
    context = {}
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        next_url = request.POST.get('next', request.GET.get('next', ''))

        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                context = {
                    'user': user
                }
                return HttpResponseRedirect(next_url)

        else:
            context = {
                'message_login_fail': "Invalid username or password"
            }
    return render(request, 'core/style/default.html', context)


def logout_user(request):
    next_url = request.POST.get('next', request.GET.get('next', ''))
    logout(request)
    return HttpResponseRedirect(next_url)


@never_cache
@login_required(login_url="user:login_user")
def change_user(request):
    """
    Profile overview and change
    """
    form = ProfileChangeForm(request.POST or None, instance=request.user)
    data_saved = False

    if form.is_valid():
        form.save()
        data_saved = True

    return render(request, 'custom_auth/change_user_data.html', {
        'form': form,
        'data_saved': data_saved
    })

project/custom_auth/templates/custom_auth/_complete_registration.html
{% extends "core/style/default_style.html" %} {% load form_tags %} {% load static %} {% block base_content %}<div class="row complete_registration"><div class="small-12 columns text-center">{{message_registration_ok}}</div></div>{% endblock %}

project/custom_auth/templates/custom_auth/_login.html
{% load form_tags %} {% load static %} {% load cms_tags sekizai_tags %} {% load i18n %}<div class="login-box">{% if not user.is_authenticated %}<div class="row register"><div class="small-6 small-offset-6 columns text-right"><a href="{% url 'user:create_user' %}">Register</a></div></div><form method="post" name="login_form_box" action="{% url 'user:login_user' %}">{% csrf_token %} <input type="hidden" name="next" value="{{ request.path }}"><div class="row collapse"><div class="large-12 columns"><input type="text" class="input" placeholder="{% trans 'Username' %}" name="username"></div><div class="large-12 columns"><input type="password" class="input" placeholder="{% trans 'Password' %}" name="password"></div></div><div class="row form-bottom collapse"><div class="small-8 medium-12 large-8 columns forgot-password"><a href="{% url 'user:password_reset' %}">{% trans 'Forgot your password?' %}</a></div><div class="small-4 medium-12 large-4 columns text-right"><button type="submit">{% trans 'Login' %}</button></div>{% if message_login_fail %}<div class="large-12 columns">{{ message_login_fail }}</div>{% endif %}</div></form>{% else %}<div class="row"><div class="large-12 columns user"><form method="post" action="{% url 'user:logout_user' %}">{% csrf_token %} <input type="hidden" name="next" value="{{ request.path }}"> <button class="button" type="submit">{% trans 'Logout' %}</button></form><div class="welcome">{% trans 'Welcome' %}</div><div class="custom_user"><img src="{% static 'core/images/icon-login-user.png' %}"><span>{{ user }}</span></div><ul><li><a href="{% url 'user:change_user_data' %}">{% trans 'Edit' %}</a></li><li><a href="{% url 'user:change_user_password' %}">{% trans 'Change' %} password</a></li></ul></div></div>{% endif %}</div>

project/custom_auth/templates/custom_auth/_password_reset_confirm.html
{% extends "core/style/default_style.html" %} {% load form_tags %} {% load static %} {% block base_content %} {% if validlink %}<div class="row"><div class="small-12 columns"><h1>Enter new password</h1><p>Please enter your new password twice so we can verify you typed it in correctly.</p><form method="post" name="reset_form" action="">{% csrf_token %}<label for="id_new_password1">New password:</label>{{ form.new_password1 }} {{ form.new_password1.errors }}<label for="id_new_password2">Confirm password:</label>{{ form.new_password2 }} {{ form.new_password2.errors }} <button id="reset_submit" type="submit" class="button-class">Change password</button></form></div></div>{% else %}<div class="row"><div class="small-12 columns"><h1>Password reset unsuccessful</h1><p>The password reset link was invalid, possibly because it has already been used. Please request a new password reset.</p></div></div>{% endif %} {% endblock %}

project/custom_auth/templates/custom_auth/_password_reset_done.html
{% extends "core/style/default_style.html" %} {% load form_tags %} {% load static i18n %} {% block base_content %}<div class="row password_reset_done"><div class="small-12 columns">{% trans "We've emailed you instructions for setting your password to the email address you submitted. You should be receiving it shortly." %}</div></div>{% endblock %}

project/custom_auth/templates/custom_auth/_password_reset_email.html
{% autoescape off %} You're receiving this email because you requested a password reset for your user account. Please go to the following page and choose a new password: {% block reset_link %} http://www.sribio.com{% url 'user:password_reset_confirm' uidb64=uid token=token %} {% endblock %} Your username, in case you've forgotten: {{ user.get_username }} Thanks for using our site! Sribio info@valagro.com www.sribio.com {% endautoescape %}

project/custom_auth/templates/custom_auth/_password_reset_form.html
{% extends "core/style/default_style.html" %} {% load form_tags cms_tags %} {% load static i18n %} {% block base_content %}<div class="row"><div class="small-12 columns"><h1 class="page_title">{% trans 'Update your password' %}</h1></div></div><div class="row"><div class="small-12 columns">{% trans "Forgot your password? Type your email address down here and we will send you instruction for set up a new one." %}</div></div><div class="row password_reset_form"><div class="medium-4 medium-offset-4 columns"><form method="post" name="reset_form" action="">{% csrf_token %}<div class="row"><div class="small-12 columns">{{ form.email.labels }} {{ form.email|addcss:"input" }} {{ form.email.errors }}</div></div><div class="row"><div class="small-12 columns text-center"><button type="submit">{% trans 'Reset my password' %}</button></div></div></form></div></div>{% endblock %}

project/custom_auth/templates/custom_auth/change_user_data.html
{% extends "core/style/default.html" %}
{% load form_tags %}
{% load static i18n %}

{% block base_content %}
    <div class="row change_user_data userpost">
        <div class="small-12 columns">
            <h1 class="page_title">{% trans 'Edita il tuo profilo' %}</h1>
            <form action="" method="post">
                {% csrf_token %}
                 <div class="row">
                    <div class="col-md-3 columns">
                        {{ form.first_name.label }}
                    </div>
                    <div class="col-md-3 columns">
                        {{ form.first_name|addcss:"input" }}
                        {{ form.first_name.errors }}
                    </div>
                    <div class="col-md-3 columns">
                        {{ form.last_name.label }}
                    </div>
                    <div class="col-md-3 columns">
                        {{ form.last_name|addcss:"input" }}
                        {{ form.last_name.errors }}
                    </div>
                    <div class="col-md-3 columns">
                        {{ form.email.label }}
                    </div>
                    <div class="col-md-3 columns">
                        {{ form.email|addcss:"input" }}
                        {{ form.email.errors }}
                    </div>
                    <div class="col-md-3 columns">
                        {{ form.username.label }}
                    </div>
                    <div class="col-md-3 columns">
                        {{ form.username|addcss:"input" }}
                        {{ form.username.errors }}
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12 columns text-center">
                        <button type="submit" class="btn btn-default">{% trans 'Aggiorna' %}</button>
                    </div>
                </div>
            </form>
        </div>
         {% if data_saved %}
            <div class="col-md-12 columns message text-center"><h2>{% trans 'Profilo aggiornato correttamente!' %}</h2></div>
        {% endif %}
    </div>
{% endblock %}

project/custom_auth/templates/custom_auth/change_user_password.html
{% extends "core/style/default.html" %}
{% load form_tags %}
{% load static i18n %}



{% block base_content %}
    <div class="row userpost">
        <div class="small-12 columns">
            <h1 class="page_title">{% trans 'Change password' %}</h1>
        </div>

        <div class="small-12 columns">
            {% trans "Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly." %}
        </div>
    </div>

    <div class="row change_user_password">
        <div class="medium-4 medium-offset-4 columns">
            <form action="" method="post" class="form-test">{% csrf_token %}
                <div class="row">
                    <div class="large-12 columns">
                        {{ form.old_password.label }}
                        {{ form.old_password|addcss:"input" }}
                        {{ form.old_password.errors }}
                    </div>

                    <div class="large-12 columns">
                        {{ form.new_password1.label }}
                        {{ form.new_password1|addcss:"input" }}
                        {{ form.new_password1.errors }}
                    </div>

                    <div class="large-12 columns">
                        {{ form.new_password2.label }}
                        {{ form.new_password2|addcss:"input" }}
                        {{ form.new_password2.errors }}
                    </div>

                    <div class="row">
                        <div class="small-12 columns text-center">
                            <button type="submit">{% trans 'Change my password' %}</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

project/custom_auth/templates/custom_auth/complete_registration.html
{% extends "core/style/default.html" %}
{% load form_tags %}
{% load static %}



{% block base_content %}

    <div class="row complete_registration userpost">
        <div class="small-12 columns text-center">
            {{message_registration_ok}}
        </div>
    </div>

{% endblock %}

project/custom_auth/templates/custom_auth/password_reset_complete.html
{% extends "core/style/default.html" %}
{% load form_tags %}
{% load static %}


{% block base_content %}

    <div class="row userpost">
        <div class="small-12 columns">
            <h1>Password reset complete</h1>
            <p>Your password has been set. You may go ahead and log in now.</p>
        </div>
    </div>

{% endblock %}

project/custom_auth/templates/custom_auth/password_reset_done.html
{% extends "core/style/default.html" %}
{% load form_tags %}
{% load static i18n %}

{% block base_content %}
    <div class="row password_reset_done userpost">
        <div class="small-12 columns">
            {% trans "We've emailed you instructions for setting your password to the email address you submitted. You should be receiving it shortly." %}
        </div>
    </div>
{% endblock %}

project/custom_auth/templates/custom_auth/password_reset_email.html
{% autoescape off %}
You're receiving this email because you requested a password reset for your user account.

Please go to the following page and choose a new password:
{% block reset_link %}
http://www.prova.com{% url 'user:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
Your username, in case you've forgotten: {{ user.get_username }}

Thanks for using our site!
prova
info@prova.com
www.prova.com

{% endautoescape %}

project/custom_auth/templates/custom_auth/password_reset_form.html
{% extends "core/style/default.html" %}
{% load form_tags cms_tags %}
{% load static i18n %}



{% block base_content %}
    <div class="row userpost">
        <div class="small-12 columns">
            <h1 class="page_title">{% trans 'Dimenticata la password?' %}</h1>
        </div>
    </div>

    <div class="row">
        <div class="small-12 columns">
            {% trans "Dimenticata la password? Inserisci la tua email e ti invieremo le istruzioni per impostarne una nuova." %}
        </div>
    </div>

    <div class="row password_reset_form">
        <div class="medium-4 medium-offset-4 columns">
            <form method="post" name="reset_form" action="">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-3 columns">
                        Indirizzo email :
                    </div>
                    <div class="col-md-8 columns pull-left">
                        {{ form.email|addcss:"input" }}
                        {{ form.email.errors }}
                    </div>
                </div>
                <div class="row">
                    <div class="small-12 columns text-center">
                        <button type="submit" class="btn btn-default">{% trans 'Reimposta la mia password' %}</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

project/custom_auth/templates/custom_auth/user_creation.html
{% extends "core/style/default.html" %}
{% load form_tags cms_tags %}
{% load static i18n %}

{% block base_content %}

    <div class="row user_creation userpost">
        <div class="small-12 columns">
            <h1 class="page_title">{% trans 'Registrazione utente' %}</h1>
            <form action="{% url 'user:create_user' %}" method="post">
                {% csrf_token %}
                <div class="row">

                    <div class="col-md-3 columns">
                        Nome
                    </div>
                    <div class="col-md-3 columns">
                        {{ form.first_name|addcss:"input" }}
                        {{ form.first_name.errors }}
                    </div>

                    <div class="col-md-3 columns">
                        Cognome
                    </div>
                    <div class="col-md-3 columns">
                        {{ form.last_name|addcss:"input" }}
                        {{ form.last_name.errors }}
                    </div>

                    <div class="col-md-3 columns">
                        {{ form.email.label }}
                    </div>
                    <div class="col-md-3 columns">
                        {{ form.email|addcss:"input" }}
                        {{ form.email.errors }}
                    </div>

                    <div class="col-md-3 columns">
                        {{ form.username.label }}
                    </div>
                    <div class="col-md-3 columns">
                        {{ form.username|addcss:"input" }}
                        {{ form.username.errors }}
                    </div>

                    <div class="col-md-3 columns">
                        {{ form.password1.label }}
                    </div>
                    <div class="col-md-3 columns">
                        {{ form.password1|addcss:"input" }}
                        {{ form.password1.errors }}
                    </div>

                    <div class="col-md-3 columns">
                        {{ form.password2.label }}
                    </div>
                    <div class="col-md-3 columns">
                        {{ form.password2|addcss:"input" }}
                        {{ form.password2.errors }}
                    </div>

                </div>

                <div class="row privacy">
                    <div class="col-md-12 columns">
                        <div class="privacy_description">{% trans ' I dati personali saranno trattati in conformità con l’informativa presente nella sezione ' %}<a
                                href="{% page_url 'privacy' %}" target="_blank">Privacy</a>
                        </div>
                    </div>
                    <div class="col-md-12 columns">
                        <div class="privacy_label">{{ form.privacy_ok|addcss:"input" }}{% trans 'Autorizzo al trattamento dei dati personali *' %}</div>
                        {{ form.privacy_ok.errors }}
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12 columns text-center">
                        <button type="submit" class="btn btn-default">{% trans 'Send' %}</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}