project/bartorelli/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.http import HttpResponse
from django.views.generic import TemplateView

from core import RunEnvironment
from core.sitemap import CMSSitemapByLanguage
from core.views import sitemap_index
from products.views import check_import, import_products

urlpatterns = i18n_patterns('',
                            url(r'^admin/', include(admin.site.urls)),
                            url(r'^accounts/', include('custom_auth.urls', namespace='user')),
                            )

if settings.DEBUG:
    urlpatterns = [
                      url(r'^import/$', check_import),
                      url(r'^import/result/$', import_products, name='import_result'),

                      url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
                          {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
                      url(r'', include('django.contrib.staticfiles.urls')),
                  ] + urlpatterns

# ==========================================================================
# robots.txt
# ==========================================================================
if RunEnvironment.current_env() == RunEnvironment.LIVE:
    urlpatterns += [
        url(r'^robots\.txt$',
            TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    ]
else:
    urlpatterns += [
        url(r'^robots\.txt$',
            lambda r: HttpResponse("User-agent: *\nDisallow: /", mimetype="text/plain")),
    ]

# ==========================================================================
# sitemap.xml
# ==========================================================================

sitemaps = {
    'cmspages': CMSSitemapByLanguage
}

urlpatterns += [
    url(r'paypal\/payment', 'core.utils.show_me_the_money', name='show_me_the_money'),
]

urlpatterns += [
    url(r'^sitemap\.xml$', sitemap_index, name="sitemap_xml_index"),
]
urlpatterns += i18n_patterns(
    # url(r'^notify/$', include('paypal.standard.ipn.urls'), name='paypal-ipn'),
    url(r'^search/$', TemplateView.as_view(template_name='core/common/google_search.html'),
        name='google-search'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='sitemap_xml'),
    url(r'^', include('cms.urls')),
)

project/contacts/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
                       url(r'^$', 'contacts.views.contact_form', name='contact_form'),
                       url(r'^branch_admin_visibility.js$', 'core.views.branch_admin_visibility_js',
                           name='branch_admin_visibility_js'),
                       url(r'^notify_changes/(?P<app_name>[\w+-]*)/(?P<model_name>[\w+-]*)/(?P<obj_pk>\d+)/',
                           'core.views.notify_changes', name='notify_changes'),
                       )

project/contacts/models.py
# -*- coding: utf-8 -*-
from django.db import models
from pleiadi_content.content.models import AdministrativeMixin
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

class Contact(AdministrativeMixin):
    CONTACT_TYPE_SERV = (
        ('reg', _('REGISTRAZIONE')),
        ('cess', _('CESSAZIONE')),
        ('mod', _('MODIFICA')),
        ('sub', _('SUBENTRO')),
        ('proro', _('PROROGA'))
    )

    CONTACT_TYPE_CONTR = (
        ('prv', _('PRIVATO')),
        ('com', _('COMMERCIALE'))
    )

    CONTACT_TYPE_PAGA = (
        ('bon', _('Bonifico')),
        ('ppc', _('Paypal/Carta di Credito'))
    )

    CONTACT_TYPE_CHOICES = (
        ('abi', _('Ad uso abitativo')),
        ('abicoage', _('Ad uso abitativo concordato-agevolato')),
        ('abiiva', _('Ad uso abitativo soggetto ad iva')),
        ('divabi', _('Ad uso diverso dall\'abitazione')),
        ('divabistriva', _('Ad uso diverso dall\'abitazione di immobile strumentale con locatore soggetto ad iva'))
    )

    YES_OR_NO = (
        ('Si', 'Si'),
        ('No', 'No')
    )

    nome_registrazione = models.CharField(_('Nome registrazione'), max_length=255, blank=False, null=False)
    datastipulacontratto = models.DateTimeField()
    datainiziolocazione = models.DateTimeField()
    dataprimascadenzacontratto = models.DateTimeField()
    tiposervizio = models.CharField(_('Tipologia di Servizio'), max_length=255, blank=False, null=False,choices = CONTACT_TYPE_SERV)
    tipocontr = models.CharField(_('Tipologia di Contratto'), max_length=255, blank=False, null=False,choices=CONTACT_TYPE_CONTR)
    tipocontratto = models.CharField(_('Tipologia di Contratto due'), max_length=255, blank=False, null=False, choices=CONTACT_TYPE_CHOICES)
    canonetot = models.DecimalField(_('Canone totale solo dei primi 12 mesi Euro (separatore decimale il "." '), max_digits=10, decimal_places=2, blank=True, null=True)
    elecodfislocatori = models.TextField(_('Elenco codici fiscale locatori (uno per riga)'), blank=True, null=True)
    elecodfislocatari = models.TextField(_('Elenco codici fiscale locatari (uno per riga)'), blank=True, null=True)

    # garanzie = models.CharField(_('Garanzie'), max_length=10, blank=True, null=True, choices=YES_OR_NO)
    # dati catastali

    classe = models.CharField(_('Classe'), max_length=10, blank=True, null=True)
    rendita = models.DecimalField(_('Rendita'), max_digits=10, decimal_places=2, blank=True, null=True)
    sezione = models.CharField(_('Sezione'), max_length=10, blank=True, null=True)
    foglio = models.CharField(_('Foglio'), max_length=10, blank=True, null=True)
    particella = models.CharField(_('Particella'), max_length=10, blank=True, null=True)
    subalterno = models.CharField(_('Subalterno'), max_length=10, blank=True, null=True)
    categoria = models.CharField(_('Categoria'), max_length=10, blank=True, null=True)
    comune = models.CharField(_('Comune'), max_length=10, blank=True, null=True)

    first_name = models.CharField(_('Nome'), max_length=255, blank=False, null=False)
    last_name = models.CharField(_('Cognome'), max_length=255, blank=False, null=False)
    email = models.EmailField(_('Email'), blank=False, null=False)
    city = models.CharField(_('Comune'), max_length=255, blank=False, null=False)
    tel = models.CharField(_('Telefono'), max_length=255, blank=True, null=True)
    message = models.TextField(_('Messaggio'), blank=True, null=True)


    contratto = models.FileField(_('Allega il contratto (formato .doc o .pdf)'), upload_to='contacts/contratti', blank=True, null=True)
    visura = models.FileField(_('Allega la visura (formato .doc o .pdf)'), upload_to='contacts/contratti', blank=True, null=True)


    privacy_ok = models.BooleanField(_('privacy_accept'))
    newsletter = models.BooleanField(_('newsletter_accept'), blank=True)
    pagato = models.BooleanField(_('pagato'), blank=True, default=False)
    calcolodovuto = models.DecimalField(_('Calcolo del dovuto'), max_digits=10, decimal_places=2, blank=True, null=True)
    modalitapagamento = models.CharField(_('Modalita di pagamento'), max_length=255, blank=False, null=False, choices=CONTACT_TYPE_PAGA)

    nrprotoade = models.CharField(_('Protocollo Ade'), max_length=255, blank=True, null=True)

    class Meta:
        verbose_name = _('Contact')
        verbose_name_plural = _('Contacts')
        ordering = ('dataprimascadenzacontratto', )


    def __unicode__(self):
        return '%s %s' % (self.first_name, self.last_name, )

project/contacts/views.py
# -*- coding: utf-8 -*-
from django.core.urlresolvers import reverse, resolve
from django.shortcuts import render, redirect, render_to_response
from contacts.forms import ContactForm
from mailing.utils import get_data_table, send_email
from django.template import loader, Context, RequestContext
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from contacts.models import Contact
from core.utils import view_that_asks_for_money
from django.contrib.auth.decorators import login_required
from decimal import Decimal, getcontext
from django.http import HttpResponse

@login_required
def contact_reg(request):
    """
    Render a lista contatti inviati
    """
    template = 'contacts/detail.html'
    current_user = request.user
    print current_user.id
    gtacont = Contact.objects.filter(created_by=current_user).order_by('creation_date')
    if request.user.is_authenticated():
        pass
    else:
        pass

    context = {
        'gtacont': gtacont
    }

    return render(request, template, context)

@login_required
def contact_form(request):
    """
    Handle the contact form

    When is valid send emails and save the contact

    :param request:
    :return:
    """
    current_app = resolve(request.path_info).namespace
    context = RequestContext(request, current_app=current_app)
    # contact_saved_url = reverse('contacts:contact_sent')
    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES, request=request)


        # if form.cleaned_data['datastipulacontratto'] > form.cleaned_data['datainiziolocazione']:
            # controlli sulle date con errore di ritorno
            # return False

        if form.is_valid():
            # calcolo del dobvuto
            contact = form.save(commit=False)
            # calcolodovuto = (form.cleaned_data['canonetot'].__float__() * 2) + 3.2;
            # getcontext().prec = 10
            # calcolodovuto = (float(form.cleaned_data['canonetot']) * 2) + 3.2;
            calcolodovuto = Decimal(((float(form.cleaned_data['canonetot']) * 2) + 3.2)).quantize(Decimal('0.01'),'ROUND_UP')
            form.cleaned_data['calcolodovuto'] = calcolodovuto
            form.data['calcolodovuto'] = calcolodovuto
            contact.calcolodovuto = calcolodovuto

            rendita = float(form.cleaned_data['rendita']) if form.cleaned_data['rendita'] else float(0)
            form.cleaned_data['rendita'] = rendita
            form.data['rendita'] = rendita
            contact.rendita = rendita

            contact.save()

            # send log email to contact manager
            mail_message_exclude_fields = ['id', 'privacy', 'creation_date', 'changed_by', 'created_by', 'changed_date', 'pagato', 'nrprotoade', ]
            subject = _('Bartorelli - Riepilogo dati contratto inviato %s %s') % (contact.first_name, contact.last_name)
            data_table = get_data_table(form, Contact._meta.fields, mail_message_exclude_fields)

            body_context = {
                'mail_title': subject,
                'data_table': data_table
            }
            t = loader.get_template('mailing/mail_data_table.html')
            body = t.render(Context(body_context))
            allegati = []
            if form.instance.contratto:
                allegati.append(form.instance.contratto.path)
            if form.instance.visura:
                allegati.append(form.instance.visura.path)
            send_email(
                from_email=settings.DEFAULT_FROM_EMAIL,
                recipients=settings.DEFAULT_TO_EMAIL,
                subject=subject,
                body=body,
                cc=(form.cleaned_data['email'],),
                bcc=settings.DEFAULT_BCC_EMAIL,
                replyto=form.cleaned_data['email'],
                allegati=(allegati)
            )

            # assegno variabili di sessione
            request.session.set_expiry(1209600)
            request.session['nome_registrazione'] = form.cleaned_data['nome_registrazione']
            request.session['first_name'] = form.cleaned_data['first_name']
            request.session['last_name'] = form.cleaned_data['last_name']
            request.session['email'] = form.cleaned_data['email']
            request.session['city'] = form.cleaned_data['city']
            request.session['tel'] = form.cleaned_data['tel']
            request.session['message'] = form.cleaned_data['message']
            request.session['elecodfislocatori'] = form.cleaned_data['elecodfislocatori']
            request.session['elecodfislocatari'] = form.cleaned_data['elecodfislocatari']
            request.session['classe'] = form.cleaned_data['classe']
            request.session['rendita'] = form.cleaned_data['rendita']
            request.session['sezione'] = form.cleaned_data['sezione']
            request.session['foglio'] = form.cleaned_data['foglio']
            request.session['particella'] = form.cleaned_data['particella']
            request.session['subalterno'] = form.cleaned_data['subalterno']
            request.session['categoria'] = form.cleaned_data['categoria']
            request.session['comune'] = form.cleaned_data['comune']

            modpag = form.cleaned_data['modalitapagamento']
            if modpag=='ppc':
                context = view_that_asks_for_money(request, form, contact.pk);
                # return render(request, 'contacts/contact_sent.html', context)
                responseret = render_to_response('contacts/contact_sent.html', context)
                return responseret
            # TODO: send courtesy email to user
            # email = form.cleaned_data['email']

            # redirect
            next_url = request.POST.get('next')
            # if next_url:
            #     return redirect(next_url)
            context = {
                'form': form,
                'modpag': form.instance.get_modalitapagamento_display()
            }
            # return render(request, 'contacts/contact_sent.html', context)
            responseret = render_to_response('contacts/contact_sent.html', context)
            return responseret
    else:
        initial = {
            'nome_registrazione': request.session.get('nome_registrazione'),
            'first_name': request.session.get('first_name') if request.session.get('first_name') else request.user.first_name,
            'last_name': request.session.get('last_name') if request.session.get('last_name') else request.user.last_name,
            'email': request.session.get('email') if request.session.get('email') else request.user.email,
            'city': request.session.get('city'),
            'tel': request.session.get('tel'),
            'message': request.session.get('message'),
            'elecodfislocatori': request.session.get('elecodfislocatori'),
            'elecodfislocatari': request.session.get('elecodfislocatari'),
            'classe': request.session.get('classe'),
            'rendita': request.session.get('rendita'),
            'sezione': request.session.get('sezione'),
            'foglio': request.session.get('foglio'),
            'particella': request.session.get('particella'),
            'subalterno': request.session.get('subalterno'),
            'categoria': request.session.get('categoria'),
            'comune': request.session.get('comune'),
        }
        form = ContactForm(request=request, initial=initial)

    context = {
        'form': form,
        # 'next': contact_saved_url
    }

    return render(request, 'contacts/contact_form.html', context)

project/contacts/templates/contacts/contact_sent.html
{% extends "core/style/default.html" %}

{% block base_content %}
    <div style="padding-top:200px;">
        Richiesta inviata con successo!!
        <br /><br />
        Procedere col pagamento col metodo selezionato : {{ modpag }}
        <br />
        {{ form.render }}
    </div>
{% endblock %}

project/contacts/templates/contacts/detail.html
{% extends "core/style/default.html" %}
{% load i18n sekizai_tags static cms_tags form_tags thumbnail %}
{% load static cms_tags menu_tags sekizai_tags %}

{% block css_app %}
    <link href="{% static "contacts/stylesheet/contacts.css" %}" rel="stylesheet">
{% endblock %}




{% block above_breadcrumb %}

    <div class="pg-opt" style="display: none">
        <div class="container">
            <div class="container" id="headerprod">
                <div class="row">
                    <div class="col-md-12 nopadding">
                        <h1>
                            {% page_attribute title %}
                        </h1>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block base_content %}


    {#    <!-- Cantine Sidebar Search Column -->#}
    <div class="container lista">
        <div class="row">
            <div class="mix col-lg-12 col-md-12 col-sm-12" data-cat="{{ forloop.counter }}">
                <section class="container">


                        {% for registrazioni in gtacont %}
                            <div class="row bt panel-group">
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <section class="panel panel-default bg-white">
                                            <div class="row">
                                                <div class="col-xs-12 col-sm-12 col-md-12 panel-heading">
                                                    <div class="section-title-wr">
                                                        <h4 class="section-title left"><b>
                                                            <a data-toggle="collapse" href="#collapse{{ forloop.counter }}" class="collapsepanel">
                                                                <div class="testo col-md-10">
                                                                    <span>{{ registrazioni.nome_registrazione }}</span> /
                                                                    <span>{{ registrazioni.get_tiposervizio_display }}</span> /
                                                                    <span>{{ registrazioni.get_tipocontr_display }}</span> /
                                                                    <span>{{ registrazioni.get_tipocontratto_display }}</span></b>
                                                                </div>
                                                                <div class="pull-right col-md-2 testo">
                                                                    {{ registrazioni.creation_date|date:"DATE_FORMAT" }}
                                                                </div>
                                                            </a>
                                                        </h4>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="panel-collapse collapse" id="collapse{{ forloop.counter }}">
                                                <div class="col-xs-12 col-sm-12 col-md-12">
                                                    <div class="news-date">
                                                        <b>Data stipula contratto :</b>
                                                        <time>{{ registrazioni.datastipulacontratto|date:"DATE_FORMAT" }}</time>
                                                        <b>Data inizio locazione :</b>
                                                        <time>{{ registrazioni.datainiziolocazione|date:"DATE_FORMAT" }}</time>
                                                        <b>Data scadenza contratto :</b>
                                                        <time>{{ registrazioni.dataprimascadenzacontratto|date:"DATE_FORMAT" }}</time>
                                                    </div>
                                                </div>
                                                <div class="col-xs-12 col-sm-12 col-md-12">
                                                    {%  if registrazioni.elecodfislocatori %}
                                                        Elenco Locatori:
                                                        <div>
                                                            {{ registrazioni.elecodfislocatori|safe }}
                                                        </div>
                                                    {% endif %}
                                                    {%  if registrazioni.elecodfislocatari %}
                                                        Elenco Locatari:
                                                        <div>
                                                            {{ registrazioni.elecodfislocatari|safe }}
                                                        </div>
                                                    {% endif %}
                                                </div>
                                                <div class="col-xs-12 col-sm-12 col-md-3">
                                                    <div class="canonetot">
                                                        Canone : {{ registrazioni.canonetot }}
                                                    </div>
                                                </div>
                                                <div class="col-xs-12 col-sm-12 col-md-3">
                                                    <div class="canonetot">
                                                       Pagato: {% if registrazioni.pagato %}SI{% else %}NO{% endif %}
                                                    </div>
                                                </div>
                                                <div class="col-xs-12 col-sm-12 col-md-3">
                                                    <div class="canonetot">
                                                        Dovuto: {{ registrazioni.calcolodovuto }}
                                                    </div>
                                                </div>
                                                {% if registrazioni.nrprotoade %}
                                                    <div class="col-xs-12 col-sm-12 col-md-3">
                                                        <div class="canonetot">
                                                            Protocollo : {{ registrazioni.nrprotoade }}
                                                        </div>
                                                    </div>
                                                {% endif %}

                                                <div class="col-xs-12 col-sm-12 col-md-12 daticatastali">
                                                    <div class="col-xs-12 col-sm-12 col-md-4">
                                                    Dati catastali (classe/sezione/foglio/particella/subalterno) <br />
                                                        {{ registrazioni.classe }} /
                                                        {{ registrazioni.sezione }} / {{ registrazioni.foglio }} / {{ registrazioni.particella }} / {{ registrazioni.subalterno }}
                                                    </div>
                                                    <div class="col-xs-12 col-sm-12 col-md-2">
                                                        Categoria : {{ registrazioni.categoria }}
                                                    </div>
                                                    <div class="col-xs-12 col-sm-12 col-md-3">
                                                        Comune : {{ registrazioni.comune }}
                                                    </div>
                                                    <div class="col-xs-12 col-sm-12 col-md-3">
                                                        Rendita : {{ registrazioni.rendita }}
                                                    </div>
                                                </div>
                                                <div class="col-xs-12 col-sm-12 col-md-6 text-center">
                                                    {% if registrazioni.contratto  %}
                                                        <a class="btn btn-default" href="{{ registrazioni.contratto.url }}" target="_blank"><span>{% trans 'DOWNLOAD CONTRATTO' %}</span></a>
                                                    {% endif %}
                                                </div>
                                                <div class="col-xs-12 col-sm-12 col-md-6 text-center">
                                                    {% if registrazioni.visura  %}
                                                        <a class="btn btn-default" href="{{ registrazioni.visura.url }}" target="_blank"><span>{% trans 'DOWNLOAD VISURA' %}</span></a>
                                                    {% endif %}
                                                </div>
                                            </div>
                                    </section>

                                </div>
                            </div>
                        {% endfor %}
                </section>

            </div>
        </div>
        <!-- /.row -->

    </div>
{% endblock %}